# Generated by Django 5.1.2 on 2025-01-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_commits', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('user', 'name', 'html_url')},
        ),
    ]
