# Generated by Django 5.1.2 on 2024-12-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success'), ('request', 'request')], default='info', max_length=20),
        ),
    ]
