# Generated by Django 5.1.2 on 2025-01-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
