# Generated by Django 5.1.2 on 2024-12-22 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_forms', '0010_alter_registration_details_registration_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 10, 40, 38, 152984)),
        ),
    ]
