# Generated by Django 5.1.2 on 2024-12-27 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_forms', '0015_answer_json_answer_question_json_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraanswer',
            name='json_answer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extraquestion',
            name='json_choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extraquestion',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('MC', 'Multiple Choice'), ('SA', 'Short Answer'), ('LA', 'Long Answer'), ('DD', 'Dropdown'), ('DT', 'Date and Time'), ('IMG', 'Image'), ('JSON', 'Json')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 27, 21, 37, 18, 323104)),
        ),
    ]
