# Generated by Django 5.1.2 on 2025-01-01 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_forms', '0017_alter_registration_details_registration_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraresponse',
            name='page_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 21, 27, 38, 832413)),
        ),
    ]
