# Generated by Django 5.1.2 on 2025-01-06 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_forms', '0018_extraresponse_page_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 20, 49, 48, 283101)),
        ),
    ]
