# Generated by Django 5.1.2 on 2025-01-07 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_forms', '0019_alter_registration_details_registration_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='multiple_submissions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 16, 35, 49, 952505)),
        ),
    ]
