# Generated by Django 5.1.2 on 2025-01-08 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_forms', '0020_form_multiple_submissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 20, 10, 8, 147564)),
        ),
    ]
