# Generated by Django 5.1.2 on 2025-01-08 17:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_alter_registration_details_registration_start'),
        ('my_forms', '0022_alter_registration_details_registration_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 23, 8, 59, 909148)),
        ),
    ]
