# Generated by Django 5.1.2 on 2025-01-09 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_forms', '0023_form_form_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 9, 17, 43, 1, 358290)),
        ),
    ]
