# Generated by Django 5.1.2 on 2025-01-13 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_forms', '0026_alter_registration_details_registration_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 16, 43, 46, 796545)),
        ),
    ]
