# Generated by Django 5.1.2 on 2025-01-13 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_forms', '0027_alter_registration_details_registration_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraquestion',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('MC', 'Multiple Choice'), ('SA', 'Short Answer'), ('LA', 'Long Answer'), ('DD', 'Dropdown'), ('DT', 'Date and Time'), ('IMG', 'Image'), ('GITHUB', 'GITHUB')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('MC', 'Multiple Choice'), ('SA', 'Short Answer'), ('LA', 'Long Answer'), ('DD', 'Dropdown'), ('DT', 'Date and Time'), ('IMG', 'Image'), ('JSON', 'Json'), ('GITHUB', 'Github')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 22, 12, 10, 942201)),
        ),
    ]
