# Generated by Django 5.1.2 on 2025-01-20 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_forms', '0036_alter_registration_details_registration_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_event',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 11, 7, 57, 388948)),
        ),
    ]
