# Generated by Django 5.1.2 on 2024-12-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_extraresponse_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraresponse',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_responses', to='event.response'),
        ),
    ]
