# Generated by Django 5.1.2 on 2024-11-26 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_form_form_type_form_image_question_choices_and_more'),
        ('home', '0004_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.userprofile'),
        ),
    ]
