# Generated by Django 5.1.2 on 2024-12-03 14:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_extraresponse_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.BooleanField()),
                ('participation_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=20)),
                ('minimum_members', models.IntegerField(default=1)),
                ('maximum_members', models.IntegerField(default=1)),
                ('registration_start', models.DateTimeField(default=datetime.datetime(2024, 12, 3, 20, 5, 4, 534143))),
                ('registration_end', models.DateTimeField()),
                ('number_of_registration', models.IntegerField(blank=True, null=True)),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_details', to='event.response')),
            ],
        ),
    ]
