# Generated by Django 5.1.2 on 2024-11-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_form_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(default='miscillineous', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='form_images/')),
                ('Model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='extradetails', to='event.form')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('TEXT', 'Text'), ('MC', 'Multiple Choice'), ('SA', 'Short Answer'), ('LA', 'Long Answer'), ('DD', 'Dropdown'), ('DT', 'Date and Time'), ('IMG', 'Image')], default='TEXT', max_length=20)),
                ('choices', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='event.extradetails')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='event.extradetails')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='event.extraquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='event.extraresponse')),
            ],
        ),
    ]
