# Generated by Django 5.1.2 on 2024-12-04 12:18

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_response_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_details',
            name='accepted_users',
            field=models.ManyToManyField(related_name='accepted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration_details',
            name='invited_users',
            field=models.ManyToManyField(related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 17, 48, 2, 880541)),
        ),
    ]
