# Generated by Django 5.1.2 on 2024-11-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_extraquestion_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extradetails',
            name='form_type',
        ),
    ]
