# Generated by Django 5.1.2 on 2024-12-21 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_registration_details_registration_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 21, 22, 20, 51, 520984)),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
