# Generated by Django 5.1.2 on 2024-12-04 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_registration_details_accepted_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_details',
            name='compulsary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration_details',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Clubs', 'Clubs'), ('Invited', 'Invited')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 21, 53, 24, 529428)),
        ),
    ]
