# Generated by Django 5.1.2 on 2024-12-21 17:15

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_registration_details_registration_start_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='accepted_users',
            field=models.ManyToManyField(blank=True, related_name='accepted_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='rejected_users',
            field=models.ManyToManyField(blank=True, related_name='rejected_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 21, 22, 45, 41, 755031)),
        ),
    ]
