# Generated by Django 5.1.2 on 2024-12-05 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_registration_details_registration_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 18, 40, 54, 353495)),
        ),
    ]
