# Generated by Django 5.1.2 on 2024-12-22 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_notification_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_notification',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team_notification',
            name='sent_from',
        ),
        migrations.RemoveField(
            model_name='team_notification',
            name='user',
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 10, 40, 38, 138369)),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Team_Notification',
        ),
    ]
