# Generated by Django 5.1.2 on 2024-12-05 17:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_registration_details_registration_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='event.registration_details'),
        ),
        migrations.AddField(
            model_name='registration_details',
            name='rejected_users',
            field=models.ManyToManyField(related_name='rejected_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='accepted_users',
            field=models.ManyToManyField(related_name='accepted_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='invited_users',
            field=models.ManyToManyField(related_name='invited_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 22, 30, 19, 459332)),
        ),
    ]
