# Generated by Django 5.1.2 on 2024-12-06 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_response_logo_response_opportunity_sub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='visibility',
            field=models.CharField(choices=[('public', 'Open publicly on Unstop'), ('invite', 'Invite Only')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 14, 27, 26, 690666)),
        ),
    ]
