# Generated by Django 5.1.2 on 2024-12-27 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_registration_details_registration_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 27, 10, 56, 17, 717138)),
        ),
    ]
