# Generated by Django 5.1.2 on 2025-01-06 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='bg_images/'),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 20, 49, 48, 254660)),
        ),
    ]
