# Generated by Django 5.1.2 on 2024-12-06 14:33

import ckeditor.fields
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_clubdata_user'),
        ('event', '0019_alter_registration_details_registration_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='about_opportunity',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Mention all the guidelines like eligibility, format, etc.', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='festival_name',
            field=models.CharField(blank=True, help_text='Name of the festival or campaign (if applicable).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='mode_of_event',
            field=models.CharField(blank=True, choices=[('online', 'Online Mode'), ('offline', 'Offline Mode')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='opportunity_title',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.clubdetails'),
        ),
        migrations.AddField(
            model_name='response',
            name='skills_to_be_assessed',
            field=models.TextField(blank=True, help_text='List required skills for participants.', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='website_url',
            field=models.URLField(blank=True, help_text="The URL can be your organization's website or an opportunity-related URL.", null=True),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 20, 3, 32, 677612)),
        ),
        migrations.AddField(
            model_name='response',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Select at least one category.', to='event.category'),
        ),
    ]
