# Generated by Django 5.1.2 on 2025-01-07 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_event_bg_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 16, 35, 49, 922100)),
        ),
    ]
