# Generated by Django 5.1.2 on 2025-01-08 14:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_alter_registration_details_registration_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Registration_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.registration_details'),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 20, 10, 8, 128761)),
        ),
    ]
