# Generated by Django 5.1.2 on 2024-12-07 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_category_response_about_opportunity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 11, 18, 13, 851669)),
        ),
    ]
