# Generated by Django 5.1.2 on 2025-01-08 15:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_event_registration_detail_and_more'),
        ('my_forms', '0022_alter_registration_details_registration_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_details_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_forms.form'),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 20, 52, 54, 240512)),
        ),
    ]
