# Generated by Django 5.1.2 on 2025-01-08 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_event_user_details_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 23, 8, 59, 877887)),
        ),
    ]
