# Generated by Django 5.1.2 on 2024-12-11 10:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_alter_registration_details_registration_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='accepted_users',
            field=models.ManyToManyField(related_name='accepted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='invited_users',
            field=models.ManyToManyField(related_name='invited_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 16, 18, 6, 325729)),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='rejected_users',
            field=models.ManyToManyField(related_name='rejected_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Event Date')),
                ('event', models.CharField(max_length=100, verbose_name='Event Description')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='event.response')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['-date'],
            },
        ),
    ]
