# Generated by Django 5.1.2 on 2024-12-12 14:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_clubdata_user'),
        ('event', '0027_registration_details_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='club',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='club.clubdetails'),
        ),
        migrations.AddField(
            model_name='registration_details',
            name='invited_club',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='club.clubdetails'),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 20, 9, 18, 433057)),
        ),
        migrations.AlterField(
            model_name='response',
            name='visibility',
            field=models.CharField(choices=[('public', 'Open publicly on Nexify'), ('invite', 'Invite Only')], default='public', max_length=10),
        ),
    ]
