# Generated by Django 5.1.2 on 2025-01-13 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_alter_event_event_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 22, 12, 10, 926303)),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 22, 12, 10, 926303)),
        ),
    ]
