# Generated by Django 5.1.2 on 2024-12-13 12:59

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_clubdata_user'),
        ('event', '0028_form_club_registration_details_invited_club_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='accepted_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='accepted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='registration_details',
            name='invited_club',
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='invited_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='invited_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 18, 29, 56, 246694)),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='rejected_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='rejected_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration_details',
            name='invited_club',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='events', to='club.clubdetails'),
        ),
    ]
