# Generated by Django 5.1.2 on 2024-12-13 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_clubdata_user'),
        ('event', '0029_alter_registration_details_accepted_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='invited_club',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='club.clubdetails'),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 18, 30, 30, 831539)),
        ),
    ]
