# Generated by Django 5.1.2 on 2024-12-13 13:01

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_alter_registration_details_invited_club_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='accepted_users',
            field=models.ManyToManyField(blank=True, related_name='accepted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 18, 31, 15, 892252)),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='rejected_users',
            field=models.ManyToManyField(blank=True, related_name='rejected_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
