# Generated by Django 5.1.2 on 2025-01-16 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_alter_event_event_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 15, 18, 55, 42953)),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 15, 18, 55, 58717)),
        ),
    ]
